# Justfile – FastAPI Template task runner
# Install: https://just.systems/en/latest/install/
# List commands: just --list

# Generated by `just setup`; absent before it, which just tolerates.
set dotenv-filename := ".env.worktree"

alias docker-logs := docker-logs-app

default:
    @just --list

# -----------------------------------------------------------------------------
# Development
# -----------------------------------------------------------------------------

# Bootstrap .env (Docker) and .env.local (Mac overrides) from the sample templates
env-init:
    #!/usr/bin/env bash
    set -euo pipefail
    for name in .env .env.local; do
        [ -f "$name" ] || { cp "$name.sample" "$name"; echo "Created $name from $name.sample"; }
    done

install:
    uv sync --locked

# Prepare this checkout: environment files, dependencies, database container, migrations
setup: env-init install
    uv run --locked python -m scripts.workflow setup

# Refuse an ambient variable that would point a command at another database
verify-env:
    @uv run --locked python -m scripts.workflow verify-env

# Run FastAPI with reload, on this checkout's port and database
dev: verify-env
    #!/usr/bin/env bash
    set -euo pipefail
    [ "${WORKTREE_READY:-}" = "1" ] || { echo "Run just setup first"; exit 1; }
    exec uv run --locked fastapi dev app/api/main.py --host 127.0.0.1 --port "$APP_PORT"

status:
    uv run --locked python -m scripts.workflow status

# -----------------------------------------------------------------------------
# Testing & Quality
# -----------------------------------------------------------------------------

# Install git hooks (pre-commit + commit-msg for Conventional Commits)
prek-install:
    uv run prek install && uv run prek install --hook-type commit-msg

prek-run:
    uv run prek run --all-files

# Run every test, including the configured BDD suite; accepts pytest arguments
[positional-arguments]
test *args:
    uv run --locked pytest "$@"

test-cov:
    uv run --locked pytest --cov=app --cov=scripts --cov-report=html --cov-report=term

test-unit:
    uv run --locked pytest -m unit

test-integration:
    uv run --locked pytest -m integration

# Empty suite is allowed; present but unbound scenarios are errors
bdd:
    #!/usr/bin/env bash
    set -euo pipefail
    uv run --locked pytest features || [ $? -eq 5 ]

lint:
    uv run --locked ruff check app/ tests/ scripts/ features/ conftest.py

format:
    uv run --locked ruff format app/ tests/ scripts/ features/ conftest.py

format-check:
    uv run --locked ruff format --check app/ tests/ scripts/ features/ conftest.py

type-check:
    uv run --locked ty check app/ scripts/

complexity:
    uv run --locked complexipy

# Structural invariants: import contracts and architecture tests. No database,
# no provisioning, so it runs on a bare checkout while you work.
architecture-check:
    uv run --locked lint-imports
    uv run --locked pytest tests/architecture -q

# just runs dependencies in order and stops at the first failure
check: lint format-check type-check complexity architecture-check test-cov

# -----------------------------------------------------------------------------
# Database
# -----------------------------------------------------------------------------

migrate: verify-env
    uv run --locked alembic upgrade head

# Usage: just migrate-create "your message"
migrate-create message: verify-env
    uv run --locked alembic revision --autogenerate -m {{quote(message)}}

migrate-down: verify-env
    uv run --locked alembic downgrade -1

migrate-history: verify-env
    uv run --locked alembic history

create-user: verify-env
    uv run --locked generate-user

# -----------------------------------------------------------------------------
# Docker
# -----------------------------------------------------------------------------

docker-build-api:
    docker build --target api -t fastapi-template:api .

# Also tagged fastapi-template-worker:latest, which Prefect expects
docker-build-worker:
    docker build --target worker -t fastapi-template:worker -t fastapi-template-worker:latest .

docker-build-migrations:
    docker build --target migrations -t fastapi-template:migrations .

# Build the migrations image and run it: catches an env.py import just check cannot
smoke-migrations: verify-env docker-build-migrations
    #!/usr/bin/env bash
    set -euo pipefail
    # .env supplies the credentials; -e overrides only what differs in-network.
    docker run --rm --network fastapi-template-dev_default \
        --env-file .env \
        -e APP_DB_HOST=postgres \
        -e APP_DB_PORT=5432 \
        -e APP_DB_NAME="$APP_DB_NAME" \
        -e SECRET_KEY="$SECRET_KEY" \
        fastapi-template:migrations

docker-build-all: docker-build-api docker-build-worker docker-build-migrations

docker-up: docker-up-app docker-up-prefect

# Builds the API image locally
docker-up-app:
    docker compose up -d

# Uses the API image from the registry; set API_IMAGE in .env
docker-up-registry:
    #!/usr/bin/env bash
    if [ -z "${API_IMAGE}" ]; then
    echo "Error: set API_IMAGE in .env (e.g. API_IMAGE=ghcr.io/org/fastapi-template:latest)"
    exit 1
    fi
    docker compose -f docker-compose.registry.yml up -d

docker-up-prefect:
    docker compose -f docker-compose.prefect.yml up -d

docker-down: docker-down-app docker-down-prefect

docker-down-app:
    docker compose down

docker-down-prefect:
    docker compose -f docker-compose.prefect.yml down

docker-logs-app:
    docker compose logs -f

docker-logs-prefect:
    docker compose -f docker-compose.prefect.yml logs -f

docker-logs-api:
    docker compose logs -f api

docker-logs-worker:
    docker compose logs -f prefect-worker

docker-logs-prefect-server:
    docker compose -f docker-compose.prefect.yml logs -f prefect-server prefect-services

docker-restart: docker-down docker-up

docker-restart-app: docker-down-app docker-up-app

docker-restart-prefect: docker-down-prefect docker-up-prefect

# -----------------------------------------------------------------------------
# Prefect
# -----------------------------------------------------------------------------

# Initialize Prefect blocks and work pool
init-prefect:
    uv run init-prefect

# Serve flows locally; needs just docker-up-prefect and PREFECT_API_URL on localhost:4200
serve-flows:
    uv run serve-flows

# -----------------------------------------------------------------------------
# Cleanup
# -----------------------------------------------------------------------------

# Remove caches and coverage artifacts
clean:
    find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
    find . -type d -name ".pytest_cache" -exec rm -rf {} + 2>/dev/null || true
    find . -type d -name ".ruff_cache" -exec rm -rf {} + 2>/dev/null || true
    find . -type d -name "*.egg-info" -exec rm -rf {} + 2>/dev/null || true
    find . -type f -name "*.pyc" -delete
    find . -type f -name "*.pyo" -delete
    find . -type f -name ".coverage" -delete
    rm -rf htmlcov/ .coverage coverage.xml

# Drop this checkout's two databases; keeps the shared development container
cleanup:
    uv run --locked python -m scripts.workflow cleanup

# Remove the application and Prefect images and volumes
clean-docker:
    docker compose down -v
    docker compose -f docker-compose.prefect.yml down -v
    docker rmi fastapi-template:api fastapi-template:worker fastapi-template:migrations 2>/dev/null || true
