"""add unique constraint on users clerk_id

Revision ID: 28a975b09a5b
Revises: 23ef48847d52
Create Date: 2026-07-19 19:27:10.755043

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "28a975b09a5b"
down_revision: Union[str, Sequence[str], None] = "23ef48847d52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_clerk_id"), table_name="users")
    op.create_index(op.f("ix_users_clerk_id"), "users", ["clerk_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_clerk_id"), table_name="users")
    op.create_index(op.f("ix_users_clerk_id"), "users", ["clerk_id"], unique=False)
    # ### end Alembic commands ###
